- name: "Install Intellij-idea"
  community.general.homebrew_cask:
    name: 'intellij-idea'
    accept_external_apps: true

- name: "Link ideavimrc"
  ansible.builtin.file:
    src: "{{ project_home }}/roles/intellij-idea/tasks/.ideavimrc"
    path: "~/.ideavimrc"
    state: link

- name: "Enable ideavim key repeat"
  shell: >
    defaults write com.jetbrains.intellij ApplePressAndHoldEnabled -bool false
