require("basic_map")

hs.hotkey.bind(HYPER_LITE, "b", launch("obsidian"))
hs.hotkey.bind(HYPER_LITE, "c", launch("chatgpt"))
hs.hotkey.bind(HYPER_LITE, "e", launch("sublime text"))
hs.hotkey.bind(HYPER_LITE, "i", launch("iTerm"))
hs.hotkey.bind(HYPER_LITE, "p", launch("IntelliJ IDEA"))
hs.hotkey.bind(HYPER_LITE, "s", launch("slack"))
hs.hotkey.bind(HYPER_LITE, "t", launch("sublime text"))
hs.hotkey.bind(HYPER_LITE, "m", launch("zoom.us"))
hs.hotkey.bind(HYPER_LITE, "o", launch("Google Chrome"))