require("basic_map")

hs.hotkey.bind(HYPER_LITE, "e", launch("poe"))
hs.hotkey.bind(HYPER_LITE, "s", launch("surge"))
-- hs.hotkey.bind(HYPER_LITE, "d", launch("Collins"))
hs.hotkey.bind(HYPER_LITE, "m", launch("NetEaseMusic"))
--hs.hotkey.bind(HYPER_LITE, "r", togglelaunch("ClashX Pro"))
hs.hotkey.bind(HYPER_LITE, "w", launch("wechat"))
-- hs.hotkey.bind(HYPER_LITE, "r", launch("trello"))
-- hs.hotkey.bind(HYPER_LITE, "t", launch("Microsoft Teams (work or school)"))
--  HYPER_LITE, "4", open("Snipaste")