require("basic_map")

hs.hotkey.bind(HYPER_LITE, ",", launch("System Settings"))
hs.hotkey.bind(HYPER_LITE, "f", function() hs.execute("open ~/Downloads") end)
-- hs.hotkey.bind(HYPER_LITE, "c", launch("chatgpt"))
hs.hotkey.bind(HYPER_LITE, "p", launch("IntelliJ IDEA"))
hs.hotkey.bind(HYPER_LITE, "i", launch("iTerm"))
hs.hotkey.bind(HYPER_LITE, "o", launch("Google Chrome"))
hs.hotkey.bind(HYPER_LITE, "n", launch("zed"))

hs.hotkey.bind(HYPER_LITE, "e", launch("poe"))
hs.hotkey.bind(HYPER_LITE, "s", launch("surge"))
-- hs.hotkey.bind(HYPER_LITE, "d", launch("Collins"))
hs.hotkey.bind(HYPER_LITE, "m", launch("NetEaseMusic"))
--hs.hotkey.bind(HYPER_LITE, "r", togglelaunch("ClashX Pro"))
hs.hotkey.bind(HYPER_LITE, "w", launch("wechat"))
-- hs.hotkey.bind(HYPER_LITE, "r", launch("trello"))
hs.hotkey.bind(HYPER_LITE, "t", launch("Microsoft Teams"))
--  HYPER_LITE, "4", open("Snipaste")