require("basic_map")

hs.hotkey.bind(HYPER_LITE, "b", launch("obsidian"))
hs.hotkey.bind(HYPER_LITE, "c", launch("chatgpt"))
hs.hotkey.bind(HYPER_LITE, "e", launch("sublime text"))
hs.hotkey.bind(HYPER_LITE, "r", togglelaunch("ClashX pro"))
hs.hotkey.bind(HYPER_LITE, "d", launch("Collins"))
hs.hotkey.bind(HYPER_LITE, "i", launch("warp"))
hs.hotkey.bind(HYPER_LITE, "p", launch("IntelliJ IDEA"))
hs.hotkey.bind(HYPER_LITE, "m", launch("Music"))
hs.hotkey.bind(HYPER_LITE, "o", launch("google chrome"))
hs.hotkey.bind(HYPER_LITE, "s", launch("Sicp"))
hs.hotkey.bind(HYPER_LITE, "w", launch("wechat"))
hs.hotkey.bind(HYPER, "b", force_break)
--  HYPER, "4", open("Snipaste")