- name: "Install Hammerspoon"
  community.general.homebrew_cask:
    name: 'hammerspoon'
    accept_external_apps: true

- name: Make .hammerspoon folder
  file:
    path: "~/.hammerspoon"
    state: directory

- name: link utils.lua
  file:
    src: "{{ project_home }}/roles/hammerspoon/tasks/utils.lua"
    path: "~/.hammerspoon/utils.lua"
    state: link
    force: true

- name: link basic_map.lua
  file:
    src: "{{ project_home }}/roles/hammerspoon/tasks/basic_map.lua"
    path: "~/.hammerspoon/basic_map.lua"
    state: link
    force: true

- name: link init.lua
  file:
    src: "{{ project_home }}/roles/hammerspoon/tasks/init.lua"
    path: "~/.hammerspoon/init.lua"
    state: link
    force: true