- name: "Install k9s"
  community.general.homebrew:
    name: 'k9s'
    state: present
    update_homebrew: no

# use `k9s info` to see where the configurations are saved
# and link views.yml

#- name: link k9s
#  file:
#    src: "~/Projects/init-osx/roles/k9s/tasks/views.yml"
#    path: "~/Library/Preferences/k9s/views.yml"
#    state: link
#    force: true

