# https://www.talkingquickly.co.uk/2021/01/macos-setup-with-ansible/

- hosts: localhost
  tasks:
    - name: "Install brew casks"
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - google-chrome
        - clashx
        - wechat
        - skype
        - microsoft-outlook
        - zoom
        - slack
        - obsidian
        - microsoft-office
        - snipaste
        - bartender
        - copyclip
        - hammerspoon
        - hyperkey
        - karabiner-elements
        - keepingyouawake
        - mirrordisplays
        - spectacle
        - stats
        - lunar
        - intellij-idea
        - rancher
        - visual-studio-code
        - sublime-text
        - sublime-merge
        - font-source-code-pro

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'mas'
          'watch'
          'git'
          'htop'
          'lorem'
          'maven'
          'mit-scheme'
          'neovim'
          'ripgrep'
          'zsh-syntax-highlighting'
          'autojump'
          'bat'
          'gource'
          'docker'
          'jenv'
          'jq'
          'tree'
          'wget'
          'tldr'
        ]
        state: present
        update_homebrew: no
