# https://www.talkingquickly.co.uk/2021/01/macos-setup-with-ansible/
- hosts: localhost
  roles:
    - chrome
    - spectacle
    - karabiner
    - hammerspoon
    - iterm2
    - bottles
    - casks
    - vim
    - ideavim
    - git
    - sublime
    - snipaste
#    - chrome # manully
    - k9s
    - obsidian
#    - zsh # manually