# https://www.talkingquickly.co.uk/2021/01/macos-setup-with-ansible/
- hosts: localhost
  roles:
#    - stats
#    - chrome
#    - sublime
#    - spectacle
#    - hyperkey
#    - karabiner
#    - hammerspoon
#    - multitouch
#    - iterm2
#    - zsh
#    - vim
#    - intellij-idea
#    - git
#    - snipaste
#    - k9s
#    - obsidian
#    - contexts
    - 1password
    - raycast
    - rancher
    - lunar
    - bartender
    - mirrordisplays
    - gifox
    - keepingyouawake
    - microsoft-office
    - skype
    - topnotch
    - wechat
