# https://www.talkingquickly.co.uk/2021/01/macos-setup-with-ansible/
- hosts: localhost
  roles:
    - prepare
    - bottles
    - casks
    - vim
    - configure_ideavim
    - configure_hammerspoon
    - configure_git
