# https://www.talkingquickly.co.uk/2021/01/macos-setup-with-ansible/

- hosts: localhost
  tasks:

    - name: 'add custom homebrew repos'
      community.general.homebrew_tap:
        name: [
          homebrew/cask-fonts
        ] 
        
    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'watch',
          'git',
          'htop',
          'neovim',
          'ripgrep',
          'autojump',
          'bat',
          'gource',
          'docker',
          'jq',
          'tree',
          'wget',
          'tldr',
        ]
        state: present
        update_homebrew: no

    - name: "Install brew casks"
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - google-chrome
        - clashx
        - wechat
        - skype
        - zoom
        - slack
        - obsidian
        - microsoft-office
        - snipaste
        - bartender
        - copyclip
        - hammerspoon
        - hyperkey
        - karabiner-elements
        - keepingyouawake
        - mirrordisplays
        - spectacle
        - stats
        - lunar
        - intellij-idea
        - rancher
        - visual-studio-code
        - sublime-text
        - sublime-merge
        - font-source-code-pro
