# https://www.talkingquickly.co.uk/2021/01/macos-setup-with-ansible/
- hosts: localhost
  roles:
    - bottles
    - casks
    - vim
    - ideavim
    - hammerspoon
    - git
    - iterm2
    - karabiner
