# https://www.talkingquickly.co.uk/2021/01/macos-setup-with-ansible/
- hosts: localhost
  roles:
    # shortcuts
    - karabiner
    - hammerspoon
    - spectacle
    - multitouch
    - raycast
#    - hyperkey
    - contexts

    # helpers
    - bartender
    - cleanshot
    - mirrordisplays
    - lunar
    - 1password
    - obsidian
#    - stats
    - keepingyouawake
    - gifox
    - localsend

    # dev
#    - iterm2 // use alacrity for better performance
    - alacrity
    - sublime
    - zsh
    - vim
    - git
    - k9s
#    - rancher
    - orbstack
    - intellij-idea

    # life
    - chrome
    - skype
    - wechat
    - microsoft-office

  vars:
    project_home: "{{ lookup('env', 'PWD') }}"
