# https://www.talkingquickly.co.uk/2021/01/macos-setup-with-ansible/
- hosts: localhost
  roles:
    - karabiner
    - hammerspoon
    - spectacle
    - multitouch
    - raycast
    - bartender
    - sublime
    - hyperkey
    - contexts
    - snipaste
    - mirrordisplays
    - stats
    - chrome
    - iterm2
    - zsh
    - vim
    - git
    - k9s
    - obsidian
    - 1password
    - lunar
    - gifox
    - keepingyouawake
    - skype
    - topnotch
    - wechat
    - microsoft-office
    - rancher
    - intellij-idea

  vars:
    project_home: "{{ lookup('env', 'PWD') }}"
