# https://www.talkingquickly.co.uk/2021/01/macos-setup-with-ansible/
- hosts: localhost
  roles:
    # shortcuts
    - karabiner
    - hammerspoon
    - rectangle
    - multitouch
    - raycast

    # helpers
    - bartender
    - cleanshot
    - mirrordisplays
    - lunar
    - 1password
    - keepingyouawake
    - gifox
    - localsend
    - topnotch

    # dev
    - alacritty
    - sublime
    - zsh
    - vim
    - git
    - k9s
    - orbstack
    - intellij-idea

    # life
    - chrome
    - skype
    - wechat
    - microsoft-office

  vars:
    project_home: "{{ lookup('env', 'PWD') }}"
