- name: Make .hammerspoon folder
  file:
    path: "~/.hammerspoon"
    state: directory

- name: Copy init.lua
  file:
    src: "~/Projects/init-osx/roles/configure_hammerspoon/tasks/init.lua"
    path: "~/.hammerspoon/init.lua"
    state: link

- name: Copy utils.lua
  file:
    src: "~/Projects/init-osx/roles/configure_hammerspoon/tasks/utils.lua"
    path: "~/.hammerspoon/utils.lua"
    state: link
