#!/bin/bash

branch_name=$(git rev-parse --abbrev-ref HEAD)
ticket_number=${branch_name%%_*}

if [[ "$branch_name" == "master" ]] || [[ "$branch_name" == "main" ]]; then
  git commit -m "$1"
else
  git commit -m "$ticket_number: $1"
fi