- name: "Install zsh"
  community.general.homebrew:
    name: 'zsh'
    state: present
    update_homebrew: no

- name: "clone zsh-auto-suggestions"
  command: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

- name: "clone zsh-syntax-highlighting"
  command: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

- name: "install autojump"
  homebrew:
    name: 'autojump'
    state: present
    update_homebrew: no

- name: "install fzf"
  homebrew:
    name: 'fzf'
    state: present
    update_homebrew: no

- name: "config fzf"
  command: $(brew --prefix)/opt/fzf/install