- name: "Install multitouch"
  community.general.homebrew_cask:
    name: 'multitouch'
    accept_external_apps: true

- name: 'link conifg'
  file:
    src: "~/Projects/init-osx/roles/multitouch/tasks/com.brassmonkery.Multitouch.plist"
    path: "~/Library/Preferences/com.brassmonkery.Multitouch.plist"
    state: link
    force: true
