- name: "Install Spectacle"
  community.general.homebrew_cask:
    name: 'spectacle'
    accept_external_apps: true

- name: "Create directory for Spectacle configs"
  file:
    path: "~/Library/Application Support/Spectacle"
    state: directory

- name: "link Spectacle config"
  file:
    src: "~/Projects/init-osx/roles/spectacle/tasks/Shortcuts.json"
    path: "~/Library/Application Support/Spectacle/Shortcuts.json"
    state: link
    force: true

