- name: Link .gitignore_global
  ansible.builtin.file:
    src: "{{ project_home }}/roles/git/tasks/.gitignore_global"
    path: "~/.gitignore_global"
    state: link
    force: true

- name: enable .gitignore_global
  command: git config --global core.excludesfile ~/.gitignore_global