- name: "Install homebrew packages"
  community.general.homebrew:
    name: [
      'zsh',
      'watch',
      'git',
      'htop',
      'neovim',
      'ripgrep',
      'autojump',
      'bat',
      'gource',
      'docker',
      'jq',
      'tree',
      'wget',
      'tldr',
      'exa',
    ]
    state: present
    update_homebrew: no
