- name: "Install brew casks"
  community.general.homebrew_cask:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
    - dozer
    - keepingyouawake
    - mirrordisplays
    - rancher
    - topnotch
    - monitorcontrol
    - raycast
