- name: "Install brew casks"
  community.general.homebrew_cask:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
    - clashx
    - wechat
    - skype
    - zoom
    - slack
    - dozer
    - microsoft-office
    - bartender
    - keepingyouawake
    - mirrordisplays
    - spectacle
    - stats
    - lunar
    - intellij-idea
    - rancher
    - visual-studio-code
    - sublime-merge
    - topnotch
    - mysql
    - racket
    - gifox
    - monitorcontrol
    - raycast
    - itsycal
