- name: "Install Sinpaste"
  community.general.homebrew_cask:
    name: 'snipaste'
    accept_external_apps: true

- name: create snipaste config directory
  ansible.builtin.file:
    path: "~/.snipaste"
    state: directory

- name: link snipaste
  file:
    src: "{{ project_home }}/roles/snipaste/tasks/config.ini"
    path: "~/.snipaste/config.ini"
    state: link
    force: true

