- name: Link .gitignore_global
  ansible.builtin.file:
    src: "~/Projects/init-osx/roles/configure_git/tasks/.gitignore_global"
    path: "~/.gitignore_global"
    state: link

- name: enable .gitignore_global
  command: git config --global core.excludesfile ~/.gitignore_global
