- name: "Install Sublime Text"
  community.general.homebrew_cask:
    name: 'sublime-text'
    state: present
    update_homebrew: no
    accept_external_apps: true

- name: "Create directory for Sublime configs"
  file:
    path: "~/Library/Application Support/Sublime Text/Packages/User"
    state: directory

- name: link sublime-text settings
  file:
    src: "~/Projects/init-osx/roles/sublime/tasks/Preferences.sublime-settings"
    path: "~/Library/Application Support/Sublime Text/Packages/User/Preferences.sublime-settings"
    state: link
    force: true

- name: link sublime-text keybindings
  file:
    src: "~/Projects/init-osx/roles/sublime/tasks/Default (OSX).sublime-keymap"
    path: "~/Library/Application Support/Sublime Text/Packages/User/Default (OSX).sublime-keymap"
    state: link
    force: true

- name: "enable key repeat for sublime"
  command: defaults write com.sublimetext.4 ApplePressAndHoldEnabled -bool false
