- name: "Install Sublime Text"
  community.general.homebrew_cask:
    name: 'sublime-text'
    state: present
    update_homebrew: no

- name: "Create directory for Sublime configs"
  file:
    path: "~/Library/Application Support/Sublime Text/Packages/User"
    state: directory

- name: link sublime-text
  file:
    src: "~/Projects/init-osx/roles/sublime/tasks/Preferences.sublime-settings"
    path: "~/Library/Application Support/Sublime Text/Packages/User/Preferences.sublime-settings"
    state: link
    force: true

