- name: "Install Iterm2"
  community.general.homebrew_cask:
    name: 'iterm2'
    accept_external_apps: true

- name: Copy iterm2.plist
  file:
    src: "{{ project_home }}/roles/iterm2/tasks/com.googlecode.iterm2.plist"
    path: "~/Library/Preferences/com.googlecode.iterm2.plist"
    state: hard # must be hard link
    force: true

- name: "Install terminal tools"
  community.general.homebrew:
    name: [
      'watch',
      'git',
      'htop',
      'ripgrep',
      'autojump',
      'bat',
      'gource',
      'tree',
      'wget',
      'tldr',
      'eza',
    ]
    state: present
    update_homebrew: no
