- name: "Install Spectacle"
  community.general.homebrew_cask:
    name: 'iterm2'

- name: Copy iterm2.plist
  file:
    src: "~/Projects/init-osx/roles/iterm2/tasks/com.googlecode.iterm2.plist"
    path: "~/Library/Preferences/com.googlecode.iterm2.plist"
    state: link
    force: true

- name: Copy iterm2.private.plist
  file:
    src: "~/Projects/init-osx/roles/iterm2/tasks/com.googlecode.iterm2.private.plist"
    path: "~/Library/Preferences/com.googlecode.iterm2.private.plist"
    state: link
    force: true
