- name: install vim plug
  ansible.builtin.command: curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: install pynvim 
  ansible.builtin.command: python3 -m pip install --user --upgrade pynvim
