- name: "Install homebrew packages"
  community.general.homebrew:
    name: 'neovim'
    state: present
    update_homebrew: no

- name: install vim plug
  ansible.builtin.command: curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: install pynvim
  ansible.builtin.command: python3 -m pip install --user --upgrade pynvim

- name: make .config/nvim folder
  file:
    path: "~/.config/nvim"
    state: directory

- name: link init.vim
  file:
    src: "~/Projects/init-osx/roles/vim/tasks/init.vim"
    path: "~/.config/nvim/init.vim"
    state: link
