- name: "Install neovim"
  community.general.homebrew:
    name: 'neovim'
    state: present
    update_homebrew: no

- name: "Install vim plug"
  shell: >
    curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: "Make .config/nvim folder"
  file:
    path: "~/.config/nvim"
    state: directory

- name: "Link init.vim"
  file:
    src: "{{ project_home }}/roles/vim/tasks/init.vim"
    path: "~/.config/nvim/init.vim"
    state: link

- name: "Install vim plug"
  shell: >
    # export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890; 
    nvim +'PlugInstall --sync' +qa
