name: Test run
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ansible
        run: brew install ansible; brew link ansible

      - name: Run playbook
        run: bash run.sh
