name: Test run
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ansible
        run: python3 -m pip install --user ansible

#      - name: Run playbook
#        uses: dawidd6/action-ansible-playbook@v2
#        with:
#          playbook: playbook.yaml

      - name: Run playbook
        run: bash run.sh
